Redesign the compass application.
AsteroidOS/asteroid-compass pull request #5
Opened 2022-07-10 13:19 UTC by MagneFire

This PR changes the look and feel of the compass application. This should make it look more in line with the AsteroidOS design scheme.

| Old | New (round) | New (rectangular) |
| ----|----|----|
| ![nar-old](https://user-images.githubusercontent.com/7857908/178146279-1c7cab2f-b22d-44d9-bb6a-71baee822286.jpg) | ![nar](https://user-images.githubusercontent.com/7857908/178146282-9f4286b6-b691-4520-99b2-ed19f479213d.jpg) | ![bel](https://user-images.githubusercontent.com/7857908/178146291-9800dfe8-50d1-4757-bc9b-929219847c06.jpg) |

Additionally the `StatusPage` is used to prompt for a calibration instead of label:
![nar-mar](https://user-images.githubusercontent.com/7857908/178146564-6eb7c083-808a-4dd2-a1d3-10fb28fca00e.jpg)
See also the relevant PR: https://github.com/AsteroidOS/qml-asteroid/pull/20/files

2022-07-10 13:38 UTC, eLtMosen requested changes
Love your compass design!

2022-07-10 13:38 UTC, eLtMosen commented on src/main.qml
> +                    text: index == 0 ? "N" :
This could be an array of `[N, NE, E ...` where the index iterates through said array?

2022-07-10 13:38 UTC, eLtMosen commented on src/main.qml
> +                    anchors.centerIn: parent
Marginal, but i can better read:
anchors {
    centerIn: parent
    verticalCenterOffset: -Math.cos(angle) * Dims.l(40)
    horizontalCenterOffset: Math.sin(angle) * Dims.l(40)
}

2022-07-10 14:47 UTC, MagneFire commented
Thanks for the feedback, this reduces the code size even more :smile: 
(I was already proud to reduce it from whatever this garbage is https://github.com/MagneFire/asteroid-compass/commit/5dcbe4cf77daabff5ea34f99846fd8ac728c27f9 :sweat_smile: )

2022-07-10 15:03 UTC, eLtMosen approved these changes

2022-07-13 14:54 UTC, merged

2022-07-13 14:54 UTC, FlorentRevest commented
Love this, thanks!